
# Hinweis zum Scannen eines Projekts
# In der Konfigurationsdatei des lokalen Sonar Scanners
# /opt/sonar-scanner/conf/sonar-scanner.properties oder C:\sonar-scanner\conf\sonar-scanner.properties
# muss die URL des Sonar-Hosts hinterlegt werden:
#
# Beispiele:
# sonar.host.url=http://localhost:9000$
# sonar.host.url=https://sonar.evaltech.de


# Hier SonarQube Project Key des in der SonarQube-GUI angelegten Projekts,
# nicht den Projektnamen eintragen
sonar.projectKey=sca_tool_evaluation

# Hier SonarQube Projektnamen eintragen
sonar.projectName=sca_tool_evaluation

# Version des Projekts
sonar.projectVersion=1.0

# Token kann auch bei Aufruf von sonar-scanner angegeben werden
# Am besten ein User Token verwenden

# Token für Tests unter sonar.evaltech.de (User-Token)
sonar.token=<REDACTED>

# Quellcode-Verzeichnisse (alle Module)
# Beispiel: sonar.sources=common,communication,server,client,benchmark,auditlogserver,examples
sonar.sources=src

# Verwendete Programmiersprache
sonar.language=python

# Pfade der erzeugten Binaries des Projekts (für die Coverage-Zuordnung) angeben
# Binaries sollten vor dem Sonar-Scan-Lauf erzeugt worden sein
# Beispiel: sonar.java.binaries=common/target/classes,\
# communication/target/classes,\
# server/target/classes,\
# client/target/classes
#sonar.java.binaries=

# Testverzeichnisse (falls man Coverage für Tests analysieren will)
# Beispiel: sonar.tests=common/src/test/java,communication/src/test/java,auditlogserver/auditlogserver_common/src/test/java
#sonar.tests=

# Die Eigenschaft sonar.test.inclusions in SonarQube bzw. SonarScanner legt fest,
# welche Dateien explizit als Testdateien erkannt und analysiert werden sollen.
# Dies überschreibt die automatische Erkennung durch Sonar.
#sonar.test.inclusions=**/*Test.java,**/*Tests.java,**/*TestCase.java

# Weitere Einstellungen
sonar.sourceEncoding=UTF-8

# Pfad zum aggregierten JaCoCo XML-Report
# Beispiel: sonar.coverage.jacoco.xmlReportPaths=project-base/target/jacoco-aggregate/jacoco.
#sonar.coverage.jacoco.xmlReportPaths=

# Python-Tests
# Pfad zum Verzeichnis mit den Tests (z. B. pytest-Tests)
#sonar.tests=tests

# Pfad zum Coverage-Report in Python-Projekten (z.B. Ausgabe von "poetry run pytest --cov=src --cov-report=xml" ist die Datei coverage.xml)
sonar.python.coverage.reportPaths=build/coverage/coverage.xml

# Python-Version
sonar.python.version=3.12

# Dateien, die nicht berücksichtigt werden sollen
# Beispiel: sonar.exclusions=**/._*,documentation/javadoc/**/*,**/*.html,**/javadoc/**/*,logs/**/*,uml/**/*,**/*.xml,*.sh,**/*Dto.java
sonar.exclusions=Reports,htmlcov

# Coverage Plugin explizit setzen (nicht zwingend, aber sinnvoll, um es explizit zu zeigen)
#sonar.java.coveragePlugin=jacoco

# Pfad zum Test-Report (evtl. bei Multi-Modul-Projekten kumuliert, etwas kompliziert, Doku lesen) 
# Beispiel: sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
#sonar.coverage.jacoco.xmlReportPaths=

# Pfade zu den im Projekt verwendeten Libraries
# Beispiel: sonar.libraries=benchmark/target/,client/target/,client/target/,common/target/,communication/target/,server/target/
#sonar.libraries=

